version: "3.8"
services:
  api:
    # image: technical_test
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container usr/src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      
    command: npm run start:dev
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000

  postgres:
    image: postgres:14.2
    container_name: postgres
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432